#[derive(Clone, Debug, Default, PartialEq)]
pub struct Snapshot {
    pub sampled_at_unix_ms: u64,
    pub uptime_ms: u64,
    pub loaded_models: u64,
    pub active_requests: u64,
    pub total_requests: u64,
    pub completed_requests: u64,
    pub failed_requests: u64,
    pub prompt_tokens: u64,
    pub completion_tokens: u64,
    pub last_tokens_per_second: Option<f64>,
    pub mean_tokens_per_second: Option<f64>,
    pub last_ttft_ms: Option<f64>,
    pub mean_ttft_ms: Option<f64>,
    pub host_total_memory_bytes: Option<u64>,
    pub host_available_memory_bytes: Option<u64>,
    pub memory_source: String,
    pub kv_total_blocks: u64,
    pub kv_used_blocks: u64,
    pub kv_cached_prefixes: u64,
    pub kv_hit_tokens: u64,
    pub kv_miss_tokens: u64,
    pub current_tokens_per_second: Option<f64>,
    pub current_prefill_tokens_per_second: Option<f64>,
    pub current_decode_tokens_per_second: Option<f64>,
    pub current_ttft_ms: Option<f64>,
    pub active_elapsed_ms: f64,
    pub active_prompt_tokens: u64,
    pub active_completion_tokens: u64,
    pub active_stage: String,
    pub last_prefill_tokens_per_second: Option<f64>,
    pub mean_prefill_tokens_per_second: Option<f64>,
    pub last_decode_tokens_per_second: Option<f64>,
    pub mean_decode_tokens_per_second: Option<f64>,
    pub gpu_utilization_percent: Option<f64>,
    pub device_temperature_celsius: Option<f64>,
    pub device_power_watts: Option<f64>,
    pub device_power_limit_watts: Option<f64>,
    pub device_name: String,
}

#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HistorySample {
    pub sampled_at_unix_ms: u64,
    pub loaded_models: u64,
    pub active_requests: u64,
    pub e2e_tokens_per_second: Option<f64>,
    pub prefill_tokens_per_second: Option<f64>,
    pub decode_tokens_per_second: Option<f64>,
    pub ttft_ms: Option<f64>,
    pub memory_total_bytes: Option<u64>,
    pub memory_available_bytes: Option<u64>,
    pub memory_source: String,
    pub kv_total_blocks: u64,
    pub kv_used_blocks: u64,
    pub total_requests: u64,
    pub failed_requests: u64,
    pub gpu_utilization_percent: Option<f64>,
    pub device_temperature_celsius: Option<f64>,
    pub device_power_watts: Option<f64>,
    pub device_power_limit_watts: Option<f64>,
}
