[package]
name = "cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mirmir"
path = "src/main.rs"

[dependencies]
clap.workspace = true
config = { path = "../config" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
libmir = { workspace = true, features = ["metal"] }

[target.'cfg(target_os = "linux")'.dependencies]
libmir = { workspace = true, features = ["cuda"] }

[target.'cfg(not(any(target_os = "macos", target_os = "linux")))'.dependencies]
libmir.workspace = true

[lints]
workspace = true
